//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 12:11:36 PM EET 
//


package com.wsclient.fs.generetad;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnumFileServerType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnumFileServerType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="KBS"/&gt;
 *     &lt;enumeration value="Evrak"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EnumFileServerType")
@XmlEnum
public enum EnumFileServerType {

    KBS("KBS"),
    @XmlEnumValue("Evrak")
    EVRAK("Evrak");
    private final String value;

    EnumFileServerType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumFileServerType fromValue(String v) {
        for (EnumFileServerType c: EnumFileServerType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
